apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vn47r3mae-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vn47r3mae-python 
  name: vn47r3mae-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vn47r3mae-python 
