apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vn47r3mae-python 
  janus-idp.io/tekton: vn47r3mae-python
  backstage.io/kubernetes-id: vn47r3mae-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vn47r3mae-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml